### ISSUE TITLE
New Notify feature does not work with announce for groups.

### ISSUE THREAD

**Issue by ehendrix23** [keatontaylor/alexa_media_player#117]
Loving the new notify functionality, especially the announce.

However, it looks like using Home Assistant groups with announce does not work.

For example, I have a group:
```
alexa_general_announce:
  view: false
  entities:
    - media_player.basement_thermostat
    - media_player.family_room
    - media_player.main_thermostat

```

Calling the service with the group and announce does not work (method can be all or speak or all).
```
}
    "title": "Front Door",
    "message": "TEST",
    "data": {
        "type": "announce",
        "method": "all"
    },
    "target": [
        "group.alexa_general_announce"
    ]
}
```

changing it to TTS works:
```
}
    "title": "Front Door",
    "message": "TEST",
    "data": {
        "type": "tts"
    },
    "target": [
        "group.alexa_general_announce"
    ]
}
```

Using announce with multiple targets works as well:
```
}
    "title": "Front Door",
    "message": "TEST",
    "data": {
        "type": "announce"
        "method": "all"
    },
    "target": [
      "media_player.basement_thermostat",
      "media_player.family_room",
      "media_player.main_thermostat"
    ]
}
```

So seems to be something with announce and using group.
