### ISSUE TITLE
Wiki looks to be wrong about notification component

### ISSUE THREAD

**Issue by mauog** [keatontaylor/alexa_media_player#184]
Reading at wiki [](https://github.com/keatontaylor/alexa_media_player/wiki/Notification-Component)
it looks that to use notification component it should be used `notify.alexa_media` service and using data filed `target` to select which device address the call to.
It worked since few day ago when I upgraded from 1.2.4 to 1.2.5
At the moment I managed to have Alexa speaking using instead `notify.alexa_media_<your_alexa_id>`
Am I doing something wrong?

**Comment by alandtse** [comment]
Thanks for reporting.  The documentation is outdated. Both should work. If you use the notify with the alexa_id in the service name, it automatically fills in the target so it's no longer necessary.  Please feel free to update the Wiki to reflect both options.

**Comment by Underknowledge** [comment]
Just here while setting up this notify first time.  
https://github.com/keatontaylor/alexa_media_player/wiki/Notification-Component#how-to-use 

``` 
      service: notify.alexa_media
      data_template:
        message: "{{ tts }}"
        data:
          type: tts
        target:
        - media_player.echo_dot
``` 
works here. 
the thing wich threw me off was the part with ` "data":{"type":"tts"},` living under data. 
but as far as I can thell this is the case in the wiki
