### ISSUE TITLE
Feature Request: SSLM

### ISSUE THREAD

**Issue by Maurotb** [keatontaylor/alexa_media_player#189]
I'ts possible to insert SSLM in notify?
Is a good feature!

**Comment by alandtse** [comment]
If you can do it in the Alexa app we can potentially mimic it. If you can't, we probably won't be able to.  Can you?

**Comment by Maurotb** [comment]
mmm in my  alexa app i can't even do tts...

**Comment by gadgetchnnel** [comment]
I've just tested this and found that it already works for notifications using the "announce" method, but not the "tts" method. For example, using the dev-service page to call the relevant service (e.g. notify.alexa_media_bedroom) with the following (using an SSML example from the [Amazon documentation](https://developer.amazon.com/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html) will make the device whisper the announcement:

`{
      "message": "<amazon:effect name='whispered'>I am not a real human.</amazon:effect>",
      "data": {
          "type":"announce",
          "method":"speak"
      }
}`

Here is the same as a script:

```
alexa_ssml_test:
  alias: Alexa SSML Test
  sequence:
    - service: notify.alexa_media_bedroom
      data:
        message: <amazon:effect name="whispered">I am not a real human.</amazon:effect>
        data:
          type: announce
          method: speak
```
