### ISSUE TITLE
Can't use templates for `target:`

### ISSUE THREAD

**Issue by Nihvel** [keatontaylor/alexa_media_player#257]
**Describe the bug**
Since the upgrade to `notify.alexa_media`, the template used for dynamically selecting the media player entities does not work any longer.
I've been trying with @Ludeeus to create a template, and sure of his skills, I accepted his suggestion, but it still does not work.
I fear it is a bug in the `alexa_media`

**To Reproduce**
Simply use this automation (changing the entities accordingly ):
```
- id: 'test speech'
  alias: Test Speech
  trigger:
  - platform: state
    entity_id: input_boolean.test_speech
    to: 'on'
    from: 'off'
  condition: []
  action:
# This works
#  - service: notify.alexa_media
#    data_template:
#      target:
#      - media_player.echo_soggiorno
#      message: 'Test'
#      data:
#        type: announce
#        method: speak
 
# This doesn't
  - service: notify.alexa_media
    data_template:
      target: >-
        {%- set data = namespace(mediaplayers=[]) -%}
        {%- set data.mediaplayers = data.mediaplayers + ['media_player.echo_soggiorno'] -%}
        {{ data.mediaplayers }}
      message: 'Test'
      data:
        type: announce
        method: speak
 
  - service: homeassistant.turn_off
    entity_id: input_boolean.test_speech
```
This template has been shrunk, unnecessary IF conditions and multiple media_player(s) were removed from my final automation.

**Expected behavior**
`notify.alexa_media : target` should be able to understand templates and dynamically select the entities, with or without the `-` "dash". 

**System details**
 - Home-assistant 0.95.4: 
 - Hassio (Yes): (Please note you may have to restart hassio 2-3 times to load the latest version of alexapy after an update. This looks like a HA bug).
 - alexa_media '1.3.1':
 - alexapy (version from `pip show alexapy` or HA startup):

**Additional context**
Thanks for this great work!

**Comment by Nihvel** [comment]
Not exactly what I thought at first, but with a bit of logic and lots of Heavy Metal, I solved this.
The key is working with `groups `and several conditions. 
The only downside is, now I have all the media players working but the `volume_set `broke.

This, because **target:**  can be: _"Friendly Name, Serial Number, entity_id, or Home Assistant Group."_ 
If using groups, the variable `{{ media_player }}` takes the name of `group.all_media_player` (example) but this group is not understood by `entity_id` -> `volume_set`.

**Comment by alandtse** [comment]
I'll take a look but do you know if this template works with any other notify components to feed an array of `entity_ids`? I'm not sure if that's supported behavior by HA for notify.

**Comment by Nihvel** [comment]
Hi, no i do not know. Since I wrote about this issue, nothing's changed. I was on holiday and now that I'm back I resumed from other tasks.
I haven't checked at this volume_set issue but since the original issue was about the notify component I think this can be closed. Sorry for replying you so late mate

**Comment by alandtse** [comment]
Ok.  For the volume_set issue, if it works for other HA components then there's a bug for us to fix here. But if it doesn't work, then it may be a HA limitation on what `volume_set` supports.

**Comment by Nihvel** [comment]
The _volume_set_ issue is not a "issue". This service wants a "entity_id" and by entity_id HA lists the entities.
Groups are not entities. This causes that it is not possible to run the service of _volume_set_ against a group. 
And the _alexa_media_ doesn't support the _entity_id_ no more, only _target:_.
It looks like that _target:_ can't understand templates for joining more media players together (this is why I opened this issue, because there is no template that works), BUT, but, after few tries I found the solution, and it is to use groups.
But _volume_set_ doesn't work with groups :/

This is how you'd use the volume_set using templates.
```
    - service: media_player.volume_set
      data_template:
        entity_id: >-
          {{ media_player }}
        volume_level: >-
          {% if now().hour >= 6 and now().hour < 10 %}
            0.5
          {% elif now().hour >= 10 and now().hour < 21 %}
            0.7
          {% else %}
            0.5
          {% endif %}
```

And this is from when alexa_media was using alexa_tts
```
    - service: media_player.alexa_tts
      data_template:
        entity_id: >
          {% if states.input_boolean.alice_is_awake.state == 'off' or states.input_boolean.juri_is_awake.state == 'off' %}
            media_player.echo_camera_da_letto
          {% else %}
            media_player.echo_soggiorno, media_player.echo_cucina
          {% endif %}
        message: >-
            {{ speech_message }}
```

To reconnect to the first message, i couldn't find any template that works with _target:_.
But i thought about using method (the following is part of a bigger script, the variable media_player is what matters here):
```
      media_player: >-
        {% if player == 'bedroom' %}
          {% set media_player = 'echo_camera_da_letto' %}
        {% elif player == 'livingroom' %}
          {% set media_player = 'echo_soggiorno' %}
        {% elif player == 'all' or player | length == 0 %}
          {% set media_player = 'group.all_media_player' %}
        {% endif %}
        {{ media_player }}
```

And this is how finally I got _target:_ to work using templates. I give it the result of the previous code where in the case of ALL (or also more than one only) I pass it a group.
```
    - service: notify.alexa_media
      data_template:
        target: >-
          {{ media_player }}
        message: >-
          <speak>
            {{ speech_message }}
        data: 
          type: announce
          method: speak
```

But again, _volume_set_ does not understand groups. So I still haven't found the way for adjusting the volume to the media players that are going to play the message.

And also, not sure if this is a issue in the code, but there is delay when the message is spoken. I've got all the ECHOes starting speaking the message with some msec delay and that's annoying. It is because of this that I was just giving up to the idea of having a message spoken throu 2 or more echoes together.

For everything you're doing, you are doing an amazing job! If it wasn't for you these echoes were useless. I didn't know that TTS does not natively work on them and I lost my mind some time ago trying to have Google Translate (also amazon polly, the IBM one and a few other) speaking through them. 
I'm not sure i did buy you a coffee, I usually do it :/ I'll fix that
